### ISSUE TITLE
WSS request method

### ISSUE THREAD

**Issue by i0x404** [abdoxfox/Bughost-Scan#2]
Hello,
There are some cloudflare ips that need to be requested with wss method in order to work and the payload is like this:

GET wss://{ssh ws account} HTTP/1.1\r\nHost: {ws ip}\r\nConnection: Upgrade\r\nUpgrade: WebSocket\r\n\r\n

Can you please add it to the script, thanks

**Comment by martwale** [comment]
> Hello, There are some cloudflare ips that need to be requested with wss method in order to work and the payload is like this:
> 
> GET wss://{ssh ws account} HTTP/1.1\r\nHost: {ws ip}\r\nConnection: Upgrade\r\nUpgrade: WebSocket\r\n\r\n
> 
> Can you please add it to the script, thanks

Please how do I add this

**Comment by abdoxfox** [comment]
Simply , change the request "payload" inside script

**Comment by martwale** [comment]
Hello boss please has anything changed in the scanner. Before starts
immediately I typed in termux cd websocket_cloudflare_Scan

python3 clflareIPscan. <http://clflareIPscan.py>py here I would be asked to
choose option 1 or 2 but this is no longer the case. Please how do I use
the script again. Please help me with the correct command usage. This used
to be the best scanner I used to know. Thanks for your support.
